[rules.generic]
Alcoholic = "The person who pulled this piece must finish a glass of water before their next turn"
Babysitters = "Anyone who has a client facing job"
Bipolar = "The picker must swap seats with another player, thereby changing the order of the game. The next person will be the person after the pickers new location"
"Bye bye" = 'The person who pulled this piece needs to drink three times and say "bye bye" after every drink'
"Catch up" = "The player who arrived last to the party must drink once"
"Centre place" = "The person who pulled this piece cannot take an edge piece for the remainder of the game"
"Cheap skate" = "The person who pulled this gets to take a sip of someone else's drink"
Chef = "Those who cooked a meal tonight drink once"
"Chinese whispers" = "Play chinese whispers, where the message passed along is a players name. Whoever's name the last person hears, must drink"
"Cj's rule" = "The player who pulled this must play the remainder of the game from the floor"
"Clothes swap" = "The person who pulled this piece must swap one item of clothing with the person to their right or the picker can drink four times"
"Community parking" = "Create a king's cup for the person who knocks over the tower to finish. This is instead of them needing to finish their own drink"
"Cone zone" = "The picker puts a traffic cone on their head for the remainder of the game"
"Construction zone" = "Balance this brick on your head until you complete your next turn"
"Couch potato" = "Every player who did not cook tonight must drink once"
"Do over" = "Put the piece back from the place you took it from and pick another piece in the same turn"
"Double or nothing" = "Take another piece from the same layer or drink three times"
"Double play" = "Whoever pulled this piece chooses another player to drink double whatever the picker drinks for the remainder of the game"
"Dr seuss" = "The picker must make a two line poem, where one of the rhyming words is the player's name. If they fail, drink twice"
"Drink 1" = "You must take one drink"
"Drink 2" = "You must drink twice"
"Drink 3" = "You must drink three times"
"Driver's ed" = "Players without their full license must drink"
"Everyone drinks" = "Every player in the game drinks once"
Finish = "The person who pulled this must complete their drink before it is their turn again"
Gambler = "The picker tells the previous player if they think the next player will choose an outside or inside piece (in confidence). If they are wrong, the picker drinks. If they are correct, the next player drinks on top of their new piece"
"Govt employee" = "Those who receive Government funds must drink once"
Grandad = "Players older than the picker must drink"
"Hand switch" = "You must play the remainder of the game using the other hand than the one you used to pull this piece"
Hosts = "Those hosting the party must drink three times"
Incognito = "Put this piece back where you picked it from and pick it again next turn. If you fail this, drink three times"
Insomniac = "Drink once for every hour you have been at the party "
Inventory = "Every player must now take one extra piece per turn for the remainder of the game"
"Irish boy" = "Drink five times"
Kayak = "The picker chooses someone to play in Rock, Paper, Scissors. The loser must drink double every time the other drinks for the rest of the game"
"Lava land" = "The floor is lava for every other player until it is the pickers turn again"
"Make a rule" = "The person who pulled this piece gets to make a rule that every other player will follow until this piece is pulled again"
"Man of god" = "Take a full layer of the tower within three turns of pulling this piece or finish their drink"
"Name genie" = "The picker take a sip for every player who they cannot name"
"No u" = "Hold this piece to use as a get out of jail free card for any effects another player tries to put on you, and they will instead take your task"
"On the dole" = "Anyone has not worked overtime in the past two months, drink twice"
Outliers = "The picker only picks the outside pieces of the tower for the remainder of the game"
"Peer pressure" = "You must drink once for every player in the game"
"Quiz time" = "Picker states an assumption about another player. If correct the person chosen drinks, if not, the picker drinks"
Reverse = "Swap the direction the game is going"
"Running man" = "The picker must run to the nearest intersection and get back before their next turn"
Santa = "The picker is Santa, grab every other player a new drink from the fridge/their boxes"
"Scar story" = "The picker must tell the story of a scar. If they refuse to, or have told the story before, they must drink twice"
Single = "Those who are not in a committed relationship must drink"
"Sneaky blinders" = "The pickers wears and alcohol box on their head until the game ends or someone else pulls this piece"
"South paw" = "The picker must take a piece after every subsequent player goes, until the beginning of their next turn"
Strip = "The picker must remove one article of clothing or drink three times"
Stumper = "The person who pulled this piece must use a word in a sentence no one else knows the meaning to, or drink three"
"Sue rule" = "The picker must drink once for every word they speak for the remainder of the game"
Taken = "Those who are in a committed relationship must take a drink"
"Team work" = "The picker takes the next players turn too"
"Thumb master" = "Nothin. Its a free pass y'all"
Toast = "Make a toast and then everyone drinks once"
Touchy = "The picker must take the first piece they touch on every subsequent turn"
"Try hards" = "First visitor to arrive a the party drinks three times"
"Visitation rights" = "All those visiting the address the party is hosted at drink three times"
Wasd = "Gamers drink"
Waterfall = "The player after the picker stops drinking when the picker stops drink, and the following player stops when they stop etc."
"Wonder twins" = "The person who pulled this piece gets to choose another person to drink whenever they do for the remainder of the game"
Woozy = "The pickers must guess the number of players currently playing; without checking; and drink the number of player's they were off by"
Younger = "Everyone younger than the person who pulled this piece must drink once"


[rules.cars]
Automatic = "Those who drive an automatic vehicle must drink once"
Manual = "All players who drive a manual vehicle must drink once"

[rules.gender]
"Same gender" = "Anyone who identifies as the pickers gender drinks once"
"Opposite gender" = "Anyone who does not identify as the pickers gender drinks once"

[rules.height]
Anton = "Any player taller than the picker must drink"
Katy = "Any player in the game who is shorter than the picker must drink"

[rules.phones]
Android = "Those with an android phone drink once"
Apple = "Those with an apple phone drink once"

[rules.voting]
Andy = "All players vote on the most sober player, and they must take one drink"
Castaway = "The picker chooses an item to bring with them if they got stranded on an island. The group votes on if it's passable or not (open to interpretation). If not, picker drinks 3 times"
Catcall = "The picker must ask a question to the group, and everyone playing gets to vote on who they think it relates to the most (E.g. who is the most drunk?). If the picker does not come up with a question, they must drink three times"
"Class clown" = "Badly describe another player's job with the rest of the group voting on who it is. If they guess correctly the picker drinks, otherwise everyone else drinks"
Classy = "The players all get to vote on who they believe is the best dressed. This person must drink"
Communism = "Everyone but the player must drink once"
Democracy = "Vote as a group on someone to drink four times"
Impression = "Do an impression of one of the players in the game while the rest of the group votes on who it is. If they guess correctly the picker drinks, otherwise everyone else drinks"
Socialite = "Everyone votes on the most extroverted person playing. The person chosen must drink twice"
"Tribal council" = "Everyone in the game votes on one person to finish their drink"
Zoomer = "The group votes on the worst player with technology, who then must drink"